# Generated by Django 4.1 on 2022-08-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
